image: atlassian/default-image:3

pipelines:
  pull-requests:
    "**":
      - step:
          name: Lint
          script:
            - echo "Running linter..."
            - make install
            - make lint
          after-script:
            - if [ $BITBUCKET_EXIT_CODE -ne 0 ]; then echo "Lint failed. PR will be declined."; exit 1; fi
      - step:
          name: Test
          script:
            - echo "Running build and tests..."
            - make test
          after-script:
            - if [ $BITBUCKET_EXIT_CODE -ne 0 ]; then echo "Build and Test failed. PR will be declined."; exit 1; fi
      - step:
          name: Security Scan [TODO]
          script:
            - echo "Running security scan..."
          after-script:
            - if [ $BITBUCKET_EXIT_CODE -ne 0 ]; then echo "Security scan failed. PR will be declined."; exit 1; fi

  branches:
    main:
      - step:
          name: Increment Patch Version
          script:
            - chmod +x semver.sh
            - ./semver.sh
