from setuptools import setup, find_packages

setup(
    name="eventbridge-client",
    version="0.4.17",
    packages=find_packages(),
    install_requires=[
        "boto3",
        "jsonschema",
        "requests",
        "pytest",
        "flake8",
        "pytest-asyncio",
        "botocore",
        "opentelemetry-instrumentation",
        "opentelemetry-instrumentation-aws-lambda",
        "opentelemetry-instrumentation-botocore",
        "opentelemetry-semantic-conventions",
        "opentelemetry-api==1.25.0",
        "opentelemetry-exporter-jaeger==1.21.0",
        "opentelemetry-exporter-jaeger-proto-grpc==1.21.0",
        "opentelemetry-exporter-jaeger-thrift==1.21.0",
        "opentelemetry-exporter-otlp-proto-common==1.25.0",
        "opentelemetry-exporter-otlp-proto-grpc==1.25.0",
        "opentelemetry-propagator-aws-xray==1.0.1",
        "opentelemetry-proto==1.25.0",
        "opentelemetry-sdk==1.25.0",
        "opentelemetry-sdk-extension-aws==2.0.2",
    ],
    author="Apurv Hajare",
    author_email="apurv@karboncard.com",
    description="A simple EventBridge client for producing and consuming events with Schema Validation.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://bitbucket.org/credit-application/eventbridge-client",
)
