name: CI Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Flake8
        run: pip3 install flake8

      - name: Run Linter
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Run Tests
        run: make test

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Security Scan
        run: echo "Running security scan..."
        # You can integrate Snyk or Bandit later
        # run: |
        #   pip3 install bandit
        #   bandit -r .

  increment-version:
    name: Increment Patch Version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: python:3.9
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Version Script
        run: |
          chmod +x semver.sh
          ./semver.sh

