name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install flake8
        run: pip install flake8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          pip install pytest
          if [ -d tests ] && [ "$(ls -A tests)" ]; then
            PYTHONPATH=. pytest tests/
          else
            echo "No tests found in the 'tests/' directory. Skipping pytest."
          fi
  security_scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Security Scan [TODO]
        run: echo "Running security scan..."

  increment_patch_version:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - uses: actions/checkout@v4
      - name: Make semver.sh executable
        run: chmod +x semver.sh
      - name: Increment Patch Version
        run: ./semver.sh

